mysql: &mysql
  adapter: mysql2
  host: "db.coding4coffee.org"
  port: 3306
  username: "diaspora_test"
  password: "rJyJG2RsP825TW4e"
#  socket: /tmp/mysql.sock
  charset: utf8
  collation: utf8_bin

postgres: &postgres
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:
  encoding: unicode


common: &common
  # Choose one of the following
  <<: *mysql
  #<<: *postgres


development:
  <<: *common
  database: diaspora_development

production:
  <<: *common
  database: diaspora_production

test:
  <<: *common
  database: "diaspora_test_<%= ENV['TEST_ENV'] %>"
